---
title: "Figure S3: MiDAS5 database evaluation using data from Mei et al. 2017"
author: "Morten K. D. Dueholm"
date: "2024-03-21"
---

## R-packages
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(patchwork)
```

## Create coverage graphs
```{r, echo=FALSE, message=FALSE, warning=FALSE}
### Function to load read mapping data
read_amp_mappings <- function(input) {
  map <- data.table::fread(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,3))
  map <- setnames(map, "V1", "ASV")
  map <- setnames(map, "V3", gsub(".*vs_(.+).b6", "\\1", paste(input)))
  map <- map[order(, readr::parse_number(ASV))]}

### Read mapping results for V1-V3
a <- read_amp_mappings("data/Mei2017_V45_ASV_vs_GTDB_bac120_ssu_reps_r214.b6")
b <- read_amp_mappings("data/Mei2017_V45_ASV_vs_GTDB_ssu_all_r214.b6")
c <- read_amp_mappings("data/Mei2017_V45_ASV_vs_GreenGenes2_2022_10.b6")
d <- read_amp_mappings("data/Mei2017_V45_ASV_vs_GreenGenes2_2022_10_seqs.b6")
e <- read_amp_mappings("data/Mei2017_V45_ASV_vs_SILVA_138.1_SSURef_NR99.b6")
f <- read_amp_mappings("data/Mei2017_V45_ASV_vs_MiDAS_4.8.1.b6")
g <- read_amp_mappings("data/Mei2017_V45_ASV_vs_MiDAS_5.2.b6 ")

# Merge all the mappings into a single data.table, sort it by ASV number, and remove NA's.
merged_map <- merge.data.table(a, b, by="ASV", all=TRUE)
merged_map <- merge.data.table(merged_map, c, by="ASV", all=TRUE)
merged_map <- merge.data.table(merged_map, d, by="ASV", all=TRUE)
merged_map <- merge.data.table(merged_map, e, by="ASV", all=TRUE)
merged_map <- merge.data.table(merged_map, f, by="ASV", all=TRUE)
merged_map <- merge.data.table(merged_map, g, by="ASV", all=TRUE)
merged_map <- merged_map[order(, readr::parse_number(ASV))]
merged_map[is.na(merged_map)] <- 0

# Read ASV table
ASVtable <- data.table::fread("data/Mei2017_V45_ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)
ASVtable <- setnames(ASVtable, 1, "ASV")
ASVtable <- ASVtable[order(, readr::parse_number(ASV))]

# Merge ASV table and mappings
df <- merge.data.table(ASVtable, merged_map, by="ASV")

# Rearrange data.table into long format with Database and SeqID as variables
df_long <- melt.data.table(df, id.vars = 1:ncol(ASVtable), measure.vars = (ncol(ASVtable)+1):(ncol(ASVtable)+ncol(merged_map)-1), variable.name = "Database", value.name = "Identity") 
df_long <- melt.data.table(df_long, id.vars = c("ASV","Database","Identity"), measure.vars = 2:ncol(ASVtable), variable.name = "SeqID", value.name = "Counts") 
df_long <- df_long[, Rel_abun := Counts/sum(Counts)*100, by=.(SeqID,Database)]

# Calculate with coverage of ASVs after subsetting based on relative abundance (>= 0.01).
coverage_V45 <-df_long[Rel_abun >= 0.01, .("coverage"=sum(Rel_abun)), by=.(SeqID,Database)][,.(mean=mean(coverage),sd=sd(coverage),n=.N), by=Database]

#Calculate fraction of ASVs with 99% matches in the reference databases
r_V45 <- df_long[Rel_abun>0.01 & Counts>0, .("Hits"=sum(Identity>=99)/.N*100,
            "detected_amplicons"=.N),
            by=.(Database,SeqID)]

#Calculate fraction of ASVs with 99% matches in the reference databases
Summary_V45 <- r_V45[, .("Mean"=mean(Hits),
                  "Sd"=sd(Hits)), 
              by=.(Database)]

## Plot histogram
p1 <- ggplot(data=r_V45, aes(x=Database, y=Hits, fill=Database)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs with high-identity references (>99% ID)") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

rm(df, df_long, a,b,c,d,e,f,g,merged_map,r)
```

## Create classification graphs for genera
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Function for importing and arranging classifications
read_amp_classifications <- function(input) {
  map <- data.table::fread(input,
                      sep = "\t",
                      header = FALSE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE,
                      select = c(1,4))
  map <- setnames(map, "V1", "ASV")
  map <- map[, Database:=gsub(".*vs_(.+).sintax", "\\1", paste(input))]
  map <- map[order(, readr::parse_number(ASV))]}

# Read classifications 
a2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GTDB_bac120_ssu_reps_r214.sintax")
b2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GTDB_ssu_all_r214.sintax")
c2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GreenGenes2_2022_10.sintax")
d2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GreenGenes2_2022_10_seqs.sintax")
e2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_SILVA_138.1_SSURef_NR99.sintax")
f2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_MiDAS_4.8.1.sintax")
g2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_MiDAS_5.2.sintax")

#Merge data into one data-table
merged_map2 <- rbind.data.frame(a2,b2,c2,d2,e2,f2,g2)

#Separate the taxonomy in ranks
merged_map2 <- merged_map2[,c("K","P","C","O","F","G","S") := tstrsplit(V4, ",", fixed=TRUE)]

#Remove unused columns
merged_map2 <- merged_map2[,V4:=NULL]
merged_map2 <- merged_map2[,K:=NULL]
merged_map2 <- merged_map2[,P:=NULL]
merged_map2 <- merged_map2[,C:=NULL]
merged_map2 <- merged_map2[,O:=NULL]
merged_map2 <- merged_map2[,F:=NULL]
merged_map2 <- merged_map2[,S:=NULL]

# Read ASV table
ASVtable <- data.table::fread("data/Mei2017_V45_ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)
ASVtable <- setnames(ASVtable, 1, "ASV")
ASVtable <- ASVtable[order(, readr::parse_number(ASV))]

# Merge ASV table and classification
df2 <- merge.data.table(ASVtable, merged_map2, by="ASV")

# Rearrange data.table into long format with Database and SeqID as variables
df_long2 <- melt.data.table(df2, id.vars = c(1,(ncol(df2)-1):(ncol(df2))), measure.vars = 2:(ncol(df2)-2), variable.name = "SeqID", value.name = "Counts") 

df_long2 <- df_long2[, Rel_abun := Counts/sum(Counts)*100, by=.(SeqID,Database)]

#Summarize data
#Calculate fraction of ASVs classified at the genus level in the reference databases
rc <- df_long2[Rel_abun>0.01 & Counts>0, .("Classified"=(.N-sum(is.na(G)))/.N*100,
            "detected_amplicons"=.N), by=.(Database,SeqID)]

#Calculate fraction of ASVs with genus level classification in the reference databases
Summary2 <- rc[,.("Mean"=mean(Classified),
            "Stdev"=sd(Classified)),
            by=.(Database)]


#Combine mapping results
rc <- rc[, Database:=factor(Database, levels=c("GTDB_bac120_ssu_reps_r214",
                                               "GTDB_ssu_all_r214",
                                               "GreenGenes2_2022_10",
                                               "GreenGenes2_2022_10_seqs",
                                               "SILVA_138.1_SSURef_NR99",
                                               "MiDAS_4.8.1",
                                               "MiDAS_5.2"))]

## Plot histogram
p2 <- ggplot(data=rc, aes(x=Database, y=Classified, fill=Database)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs classified at the genus-level") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))

rm(df2, df_long2,merged_map2,rc)
```

## Create classification graphs for species
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Read classifications 
a2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GTDB_bac120_ssu_reps_r214.sintax")
b2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GTDB_ssu_all_r214.sintax")
c2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GreenGenes2_2022_10.sintax")
d2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_GreenGenes2_2022_10_seqs.sintax")
e2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_SILVA_138.1_SSURef_NR99.sintax")
f2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_MiDAS_4.8.1.sintax")
g2 <- read_amp_classifications("data/Mei2017_V45_ASV_vs_MiDAS_5.2.sintax")

#Merge data into one data-table
merged_map3 <- rbind.data.frame(a2,b2,c2,d2,e2,f2,g2)
merged_map3 <- merged_map3[,c("K","P","C","O","F","G","S") := tstrsplit(V4, ",", fixed=TRUE)]

#Remove unused columns
merged_map3 <- merged_map3[,V4:=NULL]
merged_map3 <- merged_map3[,K:=NULL]
merged_map3 <- merged_map3[,P:=NULL]
merged_map3 <- merged_map3[,C:=NULL]
merged_map3 <- merged_map3[,O:=NULL]
merged_map3 <- merged_map3[,F:=NULL]
merged_map3 <- merged_map3[,G:=NULL]

# Read ASV table
ASVtable <- data.table::fread("data/Mei2017_V45_ASVtab.txt",
                      sep = "\t",
                      header = TRUE,
                      quote = "\"",
                      fill = TRUE,
                      check.names = FALSE,
                      stringsAsFactors = FALSE)
ASVtable <- setnames(ASVtable, 1, "ASV")
ASVtable <- ASVtable[order(, readr::parse_number(ASV))]

# Merge ASV table and mappings
df3 <- merge.data.table(ASVtable, merged_map3, by="ASV")

# Rearrange data.table into long format with Database and SeqID as variables
df_long3 <- melt.data.table(df3, id.vars = c(1,(ncol(df3)-1):(ncol(df3))), measure.vars = 2:(ncol(df3)-2), variable.name = "SeqID", value.name = "Counts") 
df_long3 <- df_long3[, Rel_abun := Counts/sum(Counts)*100, by=.(SeqID,Database)]


#Calculate fraction of ASVs with 99% matches in the reference databases

rc2 <- df_long3[Rel_abun>0.01 & Counts>0, .("Classified"=(.N-sum(is.na(S)))/.N*100,
            "detected_amplicons"=.N), by=.(Database,SeqID)]

#Calculate fraction of ASVs with species level classification in the reference databases
Summary3 <- rc2[,.("Mean"=mean(Classified),
            "Stdev"=sd(Classified)),
            by=.(Database)]

#Combine mapping results
rc2 <- rc2[, Database:=factor(Database, levels=c("GTDB_bac120_ssu_reps_r214",
                                               "GTDB_ssu_all_r214",
                                               "GreenGenes2_2022_10",
                                               "GreenGenes2_2022_10_seqs",
                                               "SILVA_138.1_SSURef_NR99",
                                               "MiDAS_4.8.1",
                                               "MiDAS_5.2"))]

## Plot histogram
p3 <- ggplot(data=rc2, aes(x=Database, y=Classified, fill=Database)) +
  theme_bw() +
  geom_violin(scale = "width") +
  geom_boxplot(width=0.1, fill="white")+
  ylab("Percent of ASVs classified at the species-level") +
  scale_fill_brewer(palette="Set2")+
  theme(axis.title.x=element_blank()) +
  scale_y_continuous(limits = c(0, 100), breaks=seq(0,100,10)) +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust = 1))
```

## Create merged graph
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
p <- p1 + p2 + p3 +plot_layout(ncol=1)
```

## Export data
```{r, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
ggsave(filename="output/FigureS3_Database_evaluation_Mei2017.pdf", plot=p, width=9, height=18, useDingbats=FALSE, limitsize=FALSE)
```